### ISSUE TITLE
Optional to Skip xorpad file when it already exists

### ISSUE THREAD

**Issue by giveup** [d0k3/Decrypt9#15]
every time  padgen  will regenerate all xorpad files.
it is possible generate the specified xorpad file?

**Comment by d0k3** [comment]
Why would you want this? I can only assume you mean the ncchinfo.bin xorpad generating feature (there's also the sdinfo.bin, TWLN and CTRNAND xorpad generating feature.

Now, for the ncchinfo.bin xorpad generating feature, all xorpads are generated in one step, and I see no use in later generating some of these xorpads anew (as the newly generated xorpads will be exactly identical).

Maybe, if you can give me an example where this (skipping existing xorpads) actually would be useful, I might think about it.

**Comment by Shadowtrance** [comment]
Only reason i can think of is because some tools for converting to cia only require the exefs xorpad and exheader xorpad for conversion. So it just cuts down time / space needed by not doing the romfs xorpad.
I know there was one version of the script that only did exheader around somewhere, i dunno where it is now though. Don't think it'd be too hard to make a copy of the existing script and change it to do only the exefs and exheader xorpads in the ncchinfo.bin.

**Comment by d0k3** [comment]
Exactly - that should be edited in the Python script rather than make some possibly uneeded changes to Decrypt9

**Comment by d0k3** [comment]
No new information here, so closed for now.
